import TodoAnalytics from "@/components/Sections/Todos/analytics";

import { difficulty, priority } from "@/types/Todos";

export const Todos = [
  // EASY (15)
  {
    id: 1,
    title: "Easy Task 1",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-01-04",
  },
  {
    id: 2,
    title: "Easy Task 2",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-02-07",
  },
  {
    id: 3,
    title: "Easy Task 3",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-03-10",
  },
  {
    id: 4,
    title: "Easy Task 4",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-04-13",
  },
  {
    id: 5,
    title: "Easy Task 5",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-05-16",
  },
  {
    id: 6,
    title: "Easy Task 6",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-06-19",
  },
  {
    id: 7,
    title: "Easy Task 7",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-07-22",
  },
  {
    id: 8,
    title: "Easy Task 8",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-08-25",
  },
  {
    id: 9,
    title: "Easy Task 9",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-09-28",
  },
  {
    id: 10,
    title: "Easy Task 10",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-10-03",
  },
  {
    id: 11,
    title: "Easy Task 11",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-11-06",
  },
  {
    id: 12,
    title: "Easy Task 12",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-12-09",
  },
  {
    id: 13,
    title: "Easy Task 13",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-01-12",
  },
  {
    id: 14,
    title: "Easy Task 14",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-02-15",
  },
  {
    id: 15,
    title: "Easy Task 15",
    description: "Easy task item",
    priority: priority.low,
    difficulty: difficulty.easy,
    date: "2026-03-18",
  },

  // MEDIUM (22)
  {
    id: 16,
    title: "Medium Task 16",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-04-21",
  },
  {
    id: 17,
    title: "Medium Task 17",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-05-24",
  },
  {
    id: 18,
    title: "Medium Task 18",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-06-27",
  },
  {
    id: 19,
    title: "Medium Task 19",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-07-02",
  },
  {
    id: 20,
    title: "Medium Task 20",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-08-05",
  },
  {
    id: 21,
    title: "Medium Task 21",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-09-08",
  },
  {
    id: 22,
    title: "Medium Task 22",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-10-11",
  },
  {
    id: 23,
    title: "Medium Task 23",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-11-14",
  },
  {
    id: 24,
    title: "Medium Task 24",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-12-17",
  },
  {
    id: 25,
    title: "Medium Task 25",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-01-20",
  },
  {
    id: 26,
    title: "Medium Task 26",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-02-23",
  },
  {
    id: 27,
    title: "Medium Task 27",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-03-26",
  },
  {
    id: 28,
    title: "Medium Task 28",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-04-01",
  },
  {
    id: 29,
    title: "Medium Task 29",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-05-04",
  },
  {
    id: 30,
    title: "Medium Task 30",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-06-07",
  },
  {
    id: 31,
    title: "Medium Task 31",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-07-10",
  },
  {
    id: 32,
    title: "Medium Task 32",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-08-13",
  },
  {
    id: 33,
    title: "Medium Task 33",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-09-16",
  },
  {
    id: 34,
    title: "Medium Task 34",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-10-19",
  },
  {
    id: 35,
    title: "Medium Task 35",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-11-22",
  },
  {
    id: 36,
    title: "Medium Task 36",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-12-25",
  },
  {
    id: 37,
    title: "Medium Task 37",
    description: "Medium task item",
    priority: priority.medium,
    difficulty: difficulty.medium,
    date: "2026-01-28",
  },

  // HARD (17)
  {
    id: 38,
    title: "Hard Task 38",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-02-03",
  },
  {
    id: 39,
    title: "Hard Task 39",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-03-06",
  },
  {
    id: 40,
    title: "Hard Task 40",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-04-09",
  },
  {
    id: 41,
    title: "Hard Task 41",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-05-12",
  },
  {
    id: 42,
    title: "Hard Task 42",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-06-15",
  },
  {
    id: 43,
    title: "Hard Task 43",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-07-18",
  },
  {
    id: 44,
    title: "Hard Task 44",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-08-21",
  },
  {
    id: 45,
    title: "Hard Task 45",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-09-24",
  },
  {
    id: 46,
    title: "Hard Task 46",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-10-27",
  },
  {
    id: 47,
    title: "Hard Task 47",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-11-02",
  },
  {
    id: 48,
    title: "Hard Task 48",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-12-05",
  },
  {
    id: 49,
    title: "Hard Task 49",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-01-08",
  },
  {
    id: 50,
    title: "Hard Task 50",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-02-11",
  },
  {
    id: 51,
    title: "Hard Task 51",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-03-14",
  },
  {
    id: 52,
    title: "Hard Task 52",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-04-17",
  },
  {
    id: 53,
    title: "Hard Task 53",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-05-20",
  },
  {
    id: 54,
    title: "Hard Task 54",
    description: "Hard task item",
    priority: priority.high,
    difficulty: difficulty.hard,
    date: "2026-06-23",
  },

  // EXPERT (12)
  {
    id: 55,
    title: "Expert Task 55",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-07-26",
  },
  {
    id: 56,
    title: "Expert Task 56",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-08-01",
  },
  {
    id: 57,
    title: "Expert Task 57",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-09-04",
  },
  {
    id: 58,
    title: "Expert Task 58",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-10-07",
  },
  {
    id: 59,
    title: "Expert Task 59",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-11-10",
  },
  {
    id: 60,
    title: "Expert Task 60",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-12-13",
  },
  {
    id: 61,
    title: "Expert Task 61",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-01-16",
  },
  {
    id: 62,
    title: "Expert Task 62",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-02-19",
  },
  {
    id: 63,
    title: "Expert Task 63",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-03-22",
  },
  {
    id: 64,
    title: "Expert Task 64",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-04-25",
  },
  {
    id: 65,
    title: "Expert Task 65",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-05-28",
  },
  {
    id: 66,
    title: "Expert Task 66",
    description: "Expert task item",
    priority: priority.urgent,
    difficulty: difficulty.expert,
    date: "2026-06-03",
  },
];

export default function TodoLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex flex-col gap-4">
      <TodoAnalytics Todos={Todos} />
      {children}
    </div>
  );
}
